Note that we now need gulp-cli globally
Instead of gulp. See the link included in the README for more
information. I got an error when I used my global gulp:

```
    gulpInst.start.apply(gulpInst, toRun);
                  ^

    TypeError: Cannot read property 'apply' of undefined
```